### ISSUE TITLE
didHide() is called everytime

### ISSUE THREAD

**Issue by goreste** [IvanVorobei/SPPermission#102]
Hi,

I noticed that the method `didHide()` of the `SPPermissionDialogDelegate` is being called when i tap on `ALLOW` button of a permission and the request popup of Apple appear.

This happens if i set the computed var `dragEnabled` to false.

Shouldn't be called only when the user tap on the close button?

Thanks,
Paolo

**Comment by IvanVorobei** [comment]
Sorry, `dragEnabled`? You are not confused, maybe another option?

**Comment by IvanVorobei** [comment]
@goreste this function is called whenever the controller is closed. If all permissions are received, the controller will close automatically and call the method `didHide()`.

When you tap `ALLOW` button, called method `didAllow()` or `didDenied()`

If you have not found a mistake in your code and are sure that the problem is on my side, please make a simple project with an example of the problem and place the link here. Thank!

**Comment by goreste** [comment]
Hi, thanks for the response. The bug was inside the `3.0.2` version. Now that i upgraded the pod i'ts fixed :)

Thanks again and compliments for the pod!

**Comment by IvanVorobei** [comment]
Thanks!)
